
paths:
  /home/word:
    get:
      tags:
        - Home
      summary: 최근에 공부한 단어 가져오기(최대 5개) API
      security:
        - Authorization: []
      responses:
        '200':
          description: 리뷰 조회 성공
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "success!"
              result:
                type: array
                example: {
                  "word_list": [
                    {
                      "word_id": 5,
                      "korean": "곰",
                      "english": "bear",
                      "image_url": "https://png.pngtree.com/png-vector/20230318/ourmid/pngtree-brown-bear-animal-transparent-on-white-png-image_6655701.png"
                    },
                    {
                      "word_id": 4,
                      "korean": "토끼",
                      "english": "rabbit",
                      "image_url": "https://png.pngtree.com/png-vector/20230318/ourmid/pngtree-brown-bear-animal-transparent-on-white-png-image_6655701.png"
                    },
                    {
                      "word_id": 3,
                      "korean": "벌",
                      "english": "bee",
                      "image_url": "https://png.pngtree.com/png-vector/20230318/ourmid/pngtree-brown-bear-animal-transparent-on-white-png-image_6655701.png"
                    },
                  ]
                }
                
        '400':
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: 잘못된 요청입니다

        '500':
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.